on:
  workflow_call:
    inputs:
      target:
        description: 'Target platform'
        required: true
        default: 'x86_64-apple-darwin'
        type: string
      slim:
        description: 'Enable slim mode'
        required: false
        default: true
        type: boolean
      use-cross:
        description: 'Enable cross-compilation'
        required: true
        default: false
        type: boolean
      os:
        description: 'Operating system'
        required: true
        default: 'macos-14'
        type: string
      version:
        description: 'Version of the release'
        default: 'latest'
        type: string
      force_release:
        description: 'force release for target from branch other than main'
        default: false
        type: boolean
    secrets:
      broker_url:
        required: false        
      broker_token:
        required: false        
jobs:
  build_workflow:
    runs-on: ${{ inputs.os }}
    env:
      SLIM: ${{ inputs.slim }}
    permissions: # only needed for release_workflow however for speed (not needing to wait for another runner to be available) we set it here
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ inputs.target }}
          toolchain: stable
        if: ${{ inputs.target != 'aarch64-unknown-freebsd' && inputs.target != 'mips64-unknown-linux-gnuabi64' && inputs.target != 'mips64el-unknown-linux-gnuabi64' && inputs.target != 'mips64-unknown-linux-muslabi64' && inputs.target != 'mips64el-unknown-linux-muslabi64' && inputs.target != 's390x-unknown-linux-musl' && inputs.target != 'riscv64gc-unknown-linux-musl' }}
      - name: Install nightly Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ inputs.target }}
          toolchain: nightly
        if: ${{ inputs.use-cross != true && env.SLIM == 'true' }}
      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
          toolchain: nightly
        if: ${{ inputs.target == 'aarch64-unknown-freebsd' || inputs.target == 's390x-unknown-linux-musl' || inputs.target == 'riscv64gc-unknown-linux-musl' }}
      # - name: Rust caching
      #   uses: Swatinem/rust-cache@v2
      - name: set MACOSX_DEPLOYMENT_TARGET to 10.9 for x86_64-apple-darwin (mavericks)
        if: ${{ inputs.target == 'x86_64-apple-darwin' }}
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.9" >> $GITHUB_ENV
      - name: set MACOSX_DEPLOYMENT_TARGET to 11.0 for aarch64-apple-darwin (big sur)
        if: ${{ inputs.target == 'aarch64-apple-darwin' }}
        run: echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
      - name: Build with cross
        # if: ${{ matrix.job.use-cross == true }}
        run: make cargo_build_release TARGET=${{ inputs.target }} SLIM=${{ inputs.slim }} USE_CROSS=${{ inputs.use-cross }}
      - name: Test with cross
        # if: ${{ matrix.job.use-cross == true }}
        run: make cargo_test
      - uses: you54f/pact-broker-in-a-box@via_ruby_test
        if: ${{ inputs.target == 'aarch64-apple-darwin' || inputs.target == 'x86_64-unknown-linux-gnu' || inputs.target == 'x86_64-pc-windows-gnu' }}
      - name: test pact-broker-cli with locally running Pact Broker
        run: ./run.sh
        env:
          PACT_BROKER_BASE_URL: http://localhost:9292
          BIN: target/${{ inputs.target }}/release/pact-broker-cli
      - uses: pactflow/actions@main
        if: ${{ inputs.target == 'aarch64-apple-darwin' }}
      - run: pact-broker publish target/pacts -r
        name: Publish pacts to hosted Pactflow Broker
        if: ${{ inputs.target == 'aarch64-apple-darwin' }}
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.broker_url }}
          PACT_BROKER_TOKEN: ${{ secrets.broker_token }}
      - name: Create dist
        id: dist
        shell: bash
        run: |
          ./prep_dist.sh ${{ inputs.target }}
      - uses: actions/upload-artifact@master
        with:
          name: ${{ inputs.target }}
          path: dist/
  # release_workflow:
  #   needs: build_workflow
  #   runs-on: ubuntu-latest
  #   if: ${{ inputs.force_release == true || github.ref == 'refs/heads/main' }}
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/download-artifact@master
  #       with:
  #         name: ${{ inputs.target }}
  #         path: dist
      - name: Publish archives and packages
        if: ${{ inputs.force_release == true || github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@master
        with:
          tag_name: v${{ inputs.version }}
          name: 'Release v${{ inputs.version }}'
          generate_release_notes: false
          body: 'Release v${{ inputs.version }}'
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
